import { Routes } from '@angular/router';
import { authGuard, accountsGuard, mdGuard, adminGuard } from './guards/auth.guard';

export const routes: Routes = [
  { path: '', redirectTo: 'login', pathMatch: 'full' },
  { path: 'login', loadComponent: () => import('./login/login.component').then(m => m.LoginComponent) },
  { path: 'set-password', loadComponent: () => import('./set-password/set-password.component').then(m => m.SetPasswordComponent) },
  { path: 'dashboard', loadComponent: () => import('./dashboard/dashboard.component').then(m => m.DashboardComponent), canActivate: [authGuard] },
  { path: 'submit', loadComponent: () => import('./submit-claim/submit-claim.component').then(m => m.SubmitClaimComponent), canActivate: [authGuard] },
  { path: 'edit/:id', loadComponent: () => import('./submit-claim/submit-claim.component').then(m => m.SubmitClaimComponent), canActivate: [authGuard] },
  { path: 'accounts', loadComponent: () => import('./accounts/accounts.component').then(m => m.AccountsComponent), canActivate: [accountsGuard] },
  { path: 'md', loadComponent: () => import('./md/md.component').then(m => m.MdComponent), canActivate: [mdGuard] },
  { path: 'po/create', loadComponent: () => import('./create-po/create-po.component').then(m => m.CreatePoComponent), canActivate: [authGuard] },
  { path: 'po/edit/:id', loadComponent: () => import('./create-po/create-po.component').then(m => m.CreatePoComponent), canActivate: [authGuard] },
  { path: 'po/view/:id', loadComponent: () => import('./view-po/view-po.component').then(m => m.ViewPoComponent), canActivate: [authGuard] },
  { path: 'profile', loadComponent: () => import('./profile/profile.component').then(m => m.ProfileComponent), canActivate: [authGuard] },
  { path: 'vendors', loadComponent: () => import('./vendors/vendors.component').then(m => m.VendorsComponent), canActivate: [authGuard] },
  { path: 'vendors/:id', loadComponent: () => import('./vendor-detail/vendor-detail.component').then(m => m.VendorDetailComponent), canActivate: [authGuard] },
  { path: 'budgets', loadComponent: () => import('./budgets/budgets.component').then(m => m.BudgetsComponent), canActivate: [accountsGuard] },
  { path: 'categories', loadComponent: () => import('./categories/categories.component').then(m => m.CategoriesComponent), canActivate: [accountsGuard] },
  { path: 'recurring', loadComponent: () => import('./recurring/recurring.component').then(m => m.RecurringComponent), canActivate: [authGuard] },
  { path: 'advance-requisition', loadComponent: () => import('./advance-requisition/advance-requisition.component').then(m => m.AdvanceRequisitionComponent), canActivate: [authGuard] },
  { path: 'advance-requisition/:id', loadComponent: () => import('./advance-requisition/advance-requisition.component').then(m => m.AdvanceRequisitionComponent), canActivate: [authGuard] },
  { path: 'invoice/export/create', loadComponent: () => import('./sales-invoice/sales-invoice.component').then(m => m.SalesInvoiceComponent), canActivate: [accountsGuard] },
  { path: 'invoice/export/:id', loadComponent: () => import('./sales-invoice/sales-invoice.component').then(m => m.SalesInvoiceComponent), canActivate: [accountsGuard] },
  { path: 'invoice/dta/create', loadComponent: () => import('./sales-invoice/sales-invoice.component').then(m => m.SalesInvoiceComponent), canActivate: [accountsGuard] },
  { path: 'invoice/dta/:id', loadComponent: () => import('./sales-invoice/sales-invoice.component').then(m => m.SalesInvoiceComponent), canActivate: [accountsGuard] },
  { path: 'customers', loadComponent: () => import('./customers/customers.component').then(m => m.CustomersComponent), canActivate: [accountsGuard] },
  { path: 'customers/:id', loadComponent: () => import('./customer-detail/customer-detail.component').then(m => m.CustomerDetailComponent), canActivate: [accountsGuard] },
  { path: 'billing', loadComponent: () => import('./billing/billing.component').then(m => m.BillingComponent), canActivate: [accountsGuard] },
  { path: 'billing/invoice/create', loadComponent: () => import('./invoice-editor/invoice-editor.component').then(m => m.InvoiceEditorComponent), canActivate: [accountsGuard], data: { docType: 'invoice' } },
  { path: 'billing/invoice/:id', loadComponent: () => import('./invoice-editor/invoice-editor.component').then(m => m.InvoiceEditorComponent), canActivate: [accountsGuard], data: { docType: 'invoice' } },
  { path: 'billing/estimate/create', loadComponent: () => import('./invoice-editor/invoice-editor.component').then(m => m.InvoiceEditorComponent), canActivate: [accountsGuard], data: { docType: 'estimate' } },
  { path: 'billing/estimate/:id', loadComponent: () => import('./invoice-editor/invoice-editor.component').then(m => m.InvoiceEditorComponent), canActivate: [accountsGuard], data: { docType: 'estimate' } },
  { path: 'billing/credit-note/create', loadComponent: () => import('./invoice-editor/invoice-editor.component').then(m => m.InvoiceEditorComponent), canActivate: [accountsGuard], data: { docType: 'credit_note' } },
  { path: 'billing/credit-note/:id', loadComponent: () => import('./invoice-editor/invoice-editor.component').then(m => m.InvoiceEditorComponent), canActivate: [accountsGuard], data: { docType: 'credit_note' } },
  { path: 'crm', loadComponent: () => import('./crm/crm.component').then(m => m.CrmComponent), canActivate: [accountsGuard] },
  { path: 'inventory', loadComponent: () => import('./inventory/inventory.component').then(m => m.InventoryComponent), canActivate: [accountsGuard] },
  { path: 'admin', loadComponent: () => import('./admin/admin.component').then(m => m.AdminComponent), canActivate: [adminGuard] },
];
